//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDemoSvcGUICli.DemoServiceSesNAClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DemoServiceSesNAClient.IDemoSvcSesNA", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IDemoSvcSesNA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetHostName", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetHostNameResponse")]
        string GetHostName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetHostName", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetHostNameResponse")]
        System.Threading.Tasks.Task<string> GetHostNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Echo", ReplyAction="http://tempuri.org/IDemoSvcSesNA/EchoResponse")]
        string Echo(string strInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Echo", ReplyAction="http://tempuri.org/IDemoSvcSesNA/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string strInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Ping", ReplyAction="http://tempuri.org/IDemoSvcSesNA/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Ping", ReplyAction="http://tempuri.org/IDemoSvcSesNA/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetHostTime", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetHostTimeResponse")]
        System.DateTime GetHostTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetHostTime", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetHostTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetHostTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/IncrementCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/IncrementCounterResponse")]
        int IncrementCounter(int IncrementAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/IncrementCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/IncrementCounterResponse")]
        System.Threading.Tasks.Task<int> IncrementCounterAsync(int IncrementAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetCounterResponse")]
        int GetCounter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/GetCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/GetCounterResponse")]
        System.Threading.Tasks.Task<int> GetCounterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/DecrementCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/DecrementCounterResponse")]
        int DecrementCounter(int DecrementAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/DecrementCounter", ReplyAction="http://tempuri.org/IDemoSvcSesNA/DecrementCounterResponse")]
        System.Threading.Tasks.Task<int> DecrementCounterAsync(int DecrementAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Delay", ReplyAction="http://tempuri.org/IDemoSvcSesNA/DelayResponse")]
        void Delay(int Duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoSvcSesNA/Delay", ReplyAction="http://tempuri.org/IDemoSvcSesNA/DelayResponse")]
        System.Threading.Tasks.Task DelayAsync(int Duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoSvcSesNAChannel : WCFDemoSvcGUICli.DemoServiceSesNAClient.IDemoSvcSesNA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoSvcSesNAClient : System.ServiceModel.ClientBase<WCFDemoSvcGUICli.DemoServiceSesNAClient.IDemoSvcSesNA>, WCFDemoSvcGUICli.DemoServiceSesNAClient.IDemoSvcSesNA {
        
        public DemoSvcSesNAClient() {
        }
        
        public DemoSvcSesNAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoSvcSesNAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoSvcSesNAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoSvcSesNAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHostName() {
            return base.Channel.GetHostName();
        }
        
        public System.Threading.Tasks.Task<string> GetHostNameAsync() {
            return base.Channel.GetHostNameAsync();
        }
        
        public string Echo(string strInput) {
            return base.Channel.Echo(strInput);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string strInput) {
            return base.Channel.EchoAsync(strInput);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public System.DateTime GetHostTime() {
            return base.Channel.GetHostTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetHostTimeAsync() {
            return base.Channel.GetHostTimeAsync();
        }
        
        public int IncrementCounter(int IncrementAmount) {
            return base.Channel.IncrementCounter(IncrementAmount);
        }
        
        public System.Threading.Tasks.Task<int> IncrementCounterAsync(int IncrementAmount) {
            return base.Channel.IncrementCounterAsync(IncrementAmount);
        }
        
        public int GetCounter() {
            return base.Channel.GetCounter();
        }
        
        public System.Threading.Tasks.Task<int> GetCounterAsync() {
            return base.Channel.GetCounterAsync();
        }
        
        public int DecrementCounter(int DecrementAmount) {
            return base.Channel.DecrementCounter(DecrementAmount);
        }
        
        public System.Threading.Tasks.Task<int> DecrementCounterAsync(int DecrementAmount) {
            return base.Channel.DecrementCounterAsync(DecrementAmount);
        }
        
        public void Delay(int Duration) {
            base.Channel.Delay(Duration);
        }
        
        public System.Threading.Tasks.Task DelayAsync(int Duration) {
            return base.Channel.DelayAsync(Duration);
        }
    }
}
