//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDemoSvcGUICli.DemoServiceClientLOCAL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFDemoSvc")]
    [System.SerializableAttribute()]
    public partial class PersonInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/WCFDemoSvc")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DemoServiceClientLOCAL.IDemoService")]
    public interface IDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetHostName", ReplyAction="http://tempuri.org/IDemoService/GetHostNameResponse")]
        string GetHostName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetHostName", ReplyAction="http://tempuri.org/IDemoService/GetHostNameResponse")]
        System.Threading.Tasks.Task<string> GetHostNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Echo", ReplyAction="http://tempuri.org/IDemoService/EchoResponse")]
        string Echo(string strInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Echo", ReplyAction="http://tempuri.org/IDemoService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string strInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Ping", ReplyAction="http://tempuri.org/IDemoService/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Ping", ReplyAction="http://tempuri.org/IDemoService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetHostTime", ReplyAction="http://tempuri.org/IDemoService/GetHostTimeResponse")]
        System.DateTime GetHostTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetHostTime", ReplyAction="http://tempuri.org/IDemoService/GetHostTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetHostTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/CauseException", ReplyAction="http://tempuri.org/IDemoService/CauseExceptionResponse")]
        void CauseException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/CauseException", ReplyAction="http://tempuri.org/IDemoService/CauseExceptionResponse")]
        System.Threading.Tasks.Task CauseExceptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GuessGender", ReplyAction="http://tempuri.org/IDemoService/GuessGenderResponse")]
        WCFDemoSvcGUICli.DemoServiceClientLOCAL.Sex GuessGender(WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GuessGender", ReplyAction="http://tempuri.org/IDemoService/GuessGenderResponse")]
        System.Threading.Tasks.Task<WCFDemoSvcGUICli.DemoServiceClientLOCAL.Sex> GuessGenderAsync(WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetPerson", ReplyAction="http://tempuri.org/IDemoService/GetPersonResponse")]
        WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetPerson", ReplyAction="http://tempuri.org/IDemoService/GetPersonResponse")]
        System.Threading.Tasks.Task<WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo> GetPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Delay", ReplyAction="http://tempuri.org/IDemoService/DelayResponse")]
        void Delay(int Duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/Delay", ReplyAction="http://tempuri.org/IDemoService/DelayResponse")]
        System.Threading.Tasks.Task DelayAsync(int Duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoServiceChannel : WCFDemoSvcGUICli.DemoServiceClientLOCAL.IDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoServiceClient : System.ServiceModel.ClientBase<WCFDemoSvcGUICli.DemoServiceClientLOCAL.IDemoService>, WCFDemoSvcGUICli.DemoServiceClientLOCAL.IDemoService {
        
        public DemoServiceClient() {
        }
        
        public DemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHostName() {
            return base.Channel.GetHostName();
        }
        
        public System.Threading.Tasks.Task<string> GetHostNameAsync() {
            return base.Channel.GetHostNameAsync();
        }
        
        public string Echo(string strInput) {
            return base.Channel.Echo(strInput);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string strInput) {
            return base.Channel.EchoAsync(strInput);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public System.DateTime GetHostTime() {
            return base.Channel.GetHostTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetHostTimeAsync() {
            return base.Channel.GetHostTimeAsync();
        }
        
        public void CauseException() {
            base.Channel.CauseException();
        }
        
        public System.Threading.Tasks.Task CauseExceptionAsync() {
            return base.Channel.CauseExceptionAsync();
        }
        
        public WCFDemoSvcGUICli.DemoServiceClientLOCAL.Sex GuessGender(WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo pi) {
            return base.Channel.GuessGender(pi);
        }
        
        public System.Threading.Tasks.Task<WCFDemoSvcGUICli.DemoServiceClientLOCAL.Sex> GuessGenderAsync(WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo pi) {
            return base.Channel.GuessGenderAsync(pi);
        }
        
        public WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<WCFDemoSvcGUICli.DemoServiceClientLOCAL.PersonInfo> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
        
        public void Delay(int Duration) {
            base.Channel.Delay(Duration);
        }
        
        public System.Threading.Tasks.Task DelayAsync(int Duration) {
            return base.Channel.DelayAsync(Duration);
        }
    }
}
